/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Sergio
 */
public class JFrameMenu extends javax.swing.JFrame {

    public int val_admin, val_auxi, estado;
    public int estadoBotones;
    public int cedula;

    public JFrameMenu() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            this.setUndecorated(true);
            this.initComponents();
            this.setExtendedState(MAXIMIZED_BOTH);
            this.JPanelAuxiliar.setVisible(false);
            this.JPanelAdmin.setVisible(false);
            this.prueba.setVisible(false);


//            rsscalelabel.RSScaleLabel.setScaleLabel(jLabel1, "src/images/logo_170_170.png");
//            rsscalelabel.RSScaleLabel.setScaleLabel(JlabelLogo1, "src/images/logo_170_170.png");

        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException err) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();
        jLabel5 = new javax.swing.JLabel();
        JPanelAdmin = new javax.swing.JPanel();
        rSButtonMetroClientes = new rsbuttom.RSButtonMetro();
        rSButtonMSalir = new rsbuttom.RSButtonMetro();
        RsBtInventario = new rsbuttom.RSButtonMetro();
        rSButtonMetroProveedor = new rsbuttom.RSButtonMetro();
        rSButtonMetroVenta = new rsbuttom.RSButtonMetro();
        rSButtonMetroGasto = new rsbuttom.RSButtonMetro();
        rSButtonSeguridad = new rsbuttom.RSButtonMetro();
        rSButtonMetroCompra = new rsbuttom.RSButtonMetro();
        rSButtonMetroCarteraC = new rsbuttom.RSButtonMetro();
        rSButtonMetroCarteraP = new rsbuttom.RSButtonMetro();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        prueba = new javax.swing.JLabel();
        JPanelAuxiliar = new javax.swing.JPanel();
        rSButtonMSalir1 = new rsbuttom.RSButtonMetro();
        rSButtonMetroCliente_ = new rsbuttom.RSButtonMetro();
        rSButtonMetroProveedor_ = new rsbuttom.RSButtonMetro();
        rSButtonMetroGasto_ = new rsbuttom.RSButtonMetro();
        rSButtonMetroVenta_ = new rsbuttom.RSButtonMetro();
        RsBtInventario_ = new rsbuttom.RSButtonMetro();
        JpanelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(109, 0, 25));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        rSButtonMetro1.setBackground(new java.awt.Color(109, 0, 25));
        rSButtonMetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/menu.png"))); // NOI18N
        rSButtonMetro1.setBorderPainted(false);
        rSButtonMetro1.setColorHover(new java.awt.Color(109, 0, 25));
        rSButtonMetro1.setColorNormal(new java.awt.Color(109, 0, 25));
        rSButtonMetro1.setColorPressed(new java.awt.Color(109, 0, 25));
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DISTRIBUIDORA DE CARNES SANTOS - MENÚ PRINCIPAL");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1114, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JPanelAdmin.setBackground(new java.awt.Color(109, 0, 25));
        JPanelAdmin.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 2, new java.awt.Color(255, 255, 255)));
        JPanelAdmin.setPreferredSize(new java.awt.Dimension(180, 461));

        rSButtonMetroClientes.setText("Clientes");
        rSButtonMetroClientes.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMetroClientes.setColorNormal(new java.awt.Color(255, 204, 204));
        rSButtonMetroClientes.setColorPressed(new java.awt.Color(51, 0, 0));
        rSButtonMetroClientes.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonMetroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetroClientesActionPerformed(evt);
            }
        });

        rSButtonMSalir.setText("Cerrar Sesión");
        rSButtonMSalir.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMSalir.setColorNormal(new java.awt.Color(255, 204, 204));
        rSButtonMSalir.setColorPressed(new java.awt.Color(51, 0, 0));
        rSButtonMSalir.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMSalirActionPerformed(evt);
            }
        });

        RsBtInventario.setText("Inventario");
        RsBtInventario.setColorHover(new java.awt.Color(204, 0, 0));
        RsBtInventario.setColorNormal(new java.awt.Color(255, 204, 204));
        RsBtInventario.setColorPressed(new java.awt.Color(51, 0, 0));
        RsBtInventario.setColorTextNormal(new java.awt.Color(0, 0, 0));
        RsBtInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RsBtInventarioActionPerformed(evt);
            }
        });

        rSButtonMetroProveedor.setText("Proveedores");
        rSButtonMetroProveedor.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMetroProveedor.setColorNormal(new java.awt.Color(255, 204, 204));
        rSButtonMetroProveedor.setColorPressed(new java.awt.Color(51, 0, 0));
        rSButtonMetroProveedor.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonMetroProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetroProveedorActionPerformed(evt);
            }
        });

        rSButtonMetroVenta.setText("Ventas");
        rSButtonMetroVenta.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMetroVenta.setColorNormal(new java.awt.Color(255, 204, 204));
        rSButtonMetroVenta.setColorPressed(new java.awt.Color(51, 0, 0));
        rSButtonMetroVenta.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonMetroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetroVentaActionPerformed(evt);
            }
        });

        rSButtonMetroGasto.setText("Gastos");
        rSButtonMetroGasto.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMetroGasto.setColorNormal(new java.awt.Color(255, 204, 204));
        rSButtonMetroGasto.setColorPressed(new java.awt.Color(51, 0, 0));
        rSButtonMetroGasto.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonMetroGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetroGastoActionPerformed(evt);
            }
        });

        rSButtonSeguridad.setText("Seguridad");
        rSButtonSeguridad.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonSeguridad.setColorNormal(new java.awt.Color(255, 204, 204));
        rSButtonSeguridad.setColorPressed(new java.awt.Color(51, 0, 0));
        rSButtonSeguridad.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonSeguridadActionPerformed(evt);
            }
        });

        rSButtonMetroCompra.setText("Compras");
        rSButtonMetroCompra.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMetroCompra.setColorNormal(new java.awt.Color(255, 204, 204));
        rSButtonMetroCompra.setColorPressed(new java.awt.Color(51, 0, 0));
        rSButtonMetroCompra.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonMetroCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetroCompraActionPerformed(evt);
            }
        });

        rSButtonMetroCarteraC.setText("Cartera Cliente");
        rSButtonMetroCarteraC.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMetroCarteraC.setColorNormal(new java.awt.Color(255, 204, 204));
        rSButtonMetroCarteraC.setColorPressed(new java.awt.Color(51, 0, 0));
        rSButtonMetroCarteraC.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonMetroCarteraC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetroCarteraCActionPerformed(evt);
            }
        });

        rSButtonMetroCarteraP.setText("Cartera Proveedor");
        rSButtonMetroCarteraP.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMetroCarteraP.setColorNormal(new java.awt.Color(255, 204, 204));
        rSButtonMetroCarteraP.setColorPressed(new java.awt.Color(51, 0, 0));
        rSButtonMetroCarteraP.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonMetroCarteraP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetroCarteraPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelAdminLayout = new javax.swing.GroupLayout(JPanelAdmin);
        JPanelAdmin.setLayout(JPanelAdminLayout);
        JPanelAdminLayout.setHorizontalGroup(
            JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSButtonSeguridad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSButtonMetroClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSButtonMSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSButtonMetroProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(rSButtonMetroGasto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSButtonMetroVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSButtonMetroCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(rSButtonMetroCarteraC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(rSButtonMetroCarteraP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(RsBtInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JPanelAdminLayout.setVerticalGroup(
            JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSButtonSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetroProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetroGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetroCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetroCarteraC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetroCarteraP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RsBtInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButtonMSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(109, 0, 25));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(255, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FECHA:");
        jLabel4.setToolTipText("");

        jLFecha.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLFecha.setForeground(new java.awt.Color(255, 255, 255));
        jLFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLFecha.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NOMBRE:");
        jLabel3.setToolTipText("");

        jLabelTipo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTipo.setText(".");
        jLabelTipo.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("USUARIO:");
        jLabel6.setToolTipText("");

        jLNombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLNombre.setText(".");
        jLNombre.setToolTipText("");

        prueba.setForeground(new java.awt.Color(109, 0, 25));
        prueba.setEnabled(false);
        prueba.setFocusable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prueba, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabelTipo)
                    .addComponent(jLabel6)
                    .addComponent(jLNombre)
                    .addComponent(prueba, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        JPanelAuxiliar.setBackground(new java.awt.Color(109, 0, 25));
        JPanelAuxiliar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 2, new java.awt.Color(255, 255, 255)));
        JPanelAuxiliar.setPreferredSize(new java.awt.Dimension(180, 297));

        rSButtonMSalir1.setText("Cerrar Sesión");
        rSButtonMSalir1.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMSalir1.setColorNormal(new java.awt.Color(255, 204, 204));
        rSButtonMSalir1.setColorPressed(new java.awt.Color(51, 0, 0));
        rSButtonMSalir1.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonMSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMSalir1ActionPerformed(evt);
            }
        });

        rSButtonMetroCliente_.setText("Clientes");
        rSButtonMetroCliente_.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMetroCliente_.setColorNormal(new java.awt.Color(255, 204, 204));
        rSButtonMetroCliente_.setColorPressed(new java.awt.Color(51, 0, 0));
        rSButtonMetroCliente_.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonMetroCliente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetroCliente_ActionPerformed(evt);
            }
        });

        rSButtonMetroProveedor_.setText("Proveedores");
        rSButtonMetroProveedor_.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMetroProveedor_.setColorNormal(new java.awt.Color(255, 204, 204));
        rSButtonMetroProveedor_.setColorPressed(new java.awt.Color(51, 0, 0));
        rSButtonMetroProveedor_.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonMetroProveedor_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetroProveedor_ActionPerformed(evt);
            }
        });

        rSButtonMetroGasto_.setText("Gastos");
        rSButtonMetroGasto_.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMetroGasto_.setColorNormal(new java.awt.Color(255, 204, 204));
        rSButtonMetroGasto_.setColorPressed(new java.awt.Color(51, 0, 0));
        rSButtonMetroGasto_.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonMetroGasto_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetroGasto_ActionPerformed(evt);
            }
        });

        rSButtonMetroVenta_.setText("Ventas");
        rSButtonMetroVenta_.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMetroVenta_.setColorNormal(new java.awt.Color(255, 204, 204));
        rSButtonMetroVenta_.setColorPressed(new java.awt.Color(51, 0, 0));
        rSButtonMetroVenta_.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonMetroVenta_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetroVenta_ActionPerformed(evt);
            }
        });

        RsBtInventario_.setText("Inventario");
        RsBtInventario_.setColorHover(new java.awt.Color(204, 0, 0));
        RsBtInventario_.setColorNormal(new java.awt.Color(255, 204, 204));
        RsBtInventario_.setColorPressed(new java.awt.Color(51, 0, 0));
        RsBtInventario_.setColorTextNormal(new java.awt.Color(0, 0, 0));
        RsBtInventario_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RsBtInventario_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelAuxiliarLayout = new javax.swing.GroupLayout(JPanelAuxiliar);
        JPanelAuxiliar.setLayout(JPanelAuxiliarLayout);
        JPanelAuxiliarLayout.setHorizontalGroup(
            JPanelAuxiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelAuxiliarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelAuxiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rSButtonMetroGasto_, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(rSButtonMetroVenta_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RsBtInventario_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSButtonMetroProveedor_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSButtonMetroCliente_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSButtonMSalir1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JPanelAuxiliarLayout.setVerticalGroup(
            JPanelAuxiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelAuxiliarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSButtonMetroCliente_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetroProveedor_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetroGasto_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetroVenta_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RsBtInventario_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButtonMSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JpanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout JpanelPrincipalLayout = new javax.swing.GroupLayout(JpanelPrincipal);
        JpanelPrincipal.setLayout(JpanelPrincipalLayout);
        JpanelPrincipalLayout.setHorizontalGroup(
            JpanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JpanelPrincipalLayout.setVerticalGroup(
            JpanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(JPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                    .addComponent(JpanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanelAuxiliar, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
  
    
    
    private void rSButtonMetroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetroClientesActionPerformed
        JFrameClientes cli = new JFrameClientes();
        cli.setVisible(true);
    }//GEN-LAST:event_rSButtonMetroClientesActionPerformed

    private void rSButtonMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMSalirActionPerformed
        JFrameLogin lol = new JFrameLogin();
        dispose();
        lol.setVisible(true);
    }//GEN-LAST:event_rSButtonMSalirActionPerformed

    private void RsBtInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RsBtInventarioActionPerformed
//        JDInventario inv = new JDInventario(this, true);
//        inv.setVisible(true);
    }//GEN-LAST:event_RsBtInventarioActionPerformed

    private void rSButtonMetroProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetroProveedorActionPerformed
        JFrameProveedor pro = new JFrameProveedor();
        pro.setVisible(true);
    }//GEN-LAST:event_rSButtonMetroProveedorActionPerformed

    private void rSButtonMetroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetroVentaActionPerformed
////        JDVentas ventas = new JDVentas(this, rootPaneCheckingEnabled);
//        ventas.setTitle("Panel para la gestión de ventas");
//        ventas.setVisible(true);
    }//GEN-LAST:event_rSButtonMetroVentaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        MostrarFechaYHora();
    }//GEN-LAST:event_formWindowOpened

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
//        Animacion.mover_izquierda(1300, 500, 0, 2, JPanelDash);
        estados();
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void rSButtonMetroGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetroGastoActionPerformed
        JFrameGastos gastos = new JFrameGastos();
        gastos.tomarFecha(Integer.parseInt(prueba.getText()));
        gastos.setVisible(true);
    }//GEN-LAST:event_rSButtonMetroGastoActionPerformed

    private void rSButtonSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonSeguridadActionPerformed
        JFrameSeguridad segiridad = new JFrameSeguridad();
        segiridad.setVisible(true);

    }//GEN-LAST:event_rSButtonSeguridadActionPerformed

    private void rSButtonMetroCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetroCompraActionPerformed
//        JDCompras seg = new JDCompras(this, rootPaneCheckingEnabled);
//        seg.setTitle("Panel para la gestión de compras");
//        seg.setVisible(true);
    }//GEN-LAST:event_rSButtonMetroCompraActionPerformed

    private void rSButtonMetroCarteraCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetroCarteraCActionPerformed

    }//GEN-LAST:event_rSButtonMetroCarteraCActionPerformed

    private void rSButtonMetroCarteraPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetroCarteraPActionPerformed
//        JDCarteraProveedor cp = new JDCarteraProveedor(this, rootPaneCheckingEnabled);
//        cp.setTitle("Panel para la gestión de proveedores");
//        cp.setVisible(true);
    }//GEN-LAST:event_rSButtonMetroCarteraPActionPerformed

    private void RsBtInventario_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RsBtInventario_ActionPerformed
//        JDInventario inv = new JDInventario(this, rootPaneCheckingEnabled);
//        inv.setTitle("Panel para la gestión de inventario");
//        inv.setVisible(true);
    }//GEN-LAST:event_RsBtInventario_ActionPerformed

    private void rSButtonMetroVenta_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetroVenta_ActionPerformed
//        JDVentas ventas = new JDVentas(this, rootPaneCheckingEnabled);
//        ventas.setTitle("Panel para la gestión de ventas");
//        ventas.setVisible(true);
    }//GEN-LAST:event_rSButtonMetroVenta_ActionPerformed

    private void rSButtonMetroGasto_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetroGasto_ActionPerformed
        JFrameGastos gastos = new JFrameGastos();
        gastos.tomarFecha(Integer.parseInt(prueba.getText()));
        gastos.setVisible(true);
    }//GEN-LAST:event_rSButtonMetroGasto_ActionPerformed

    private void rSButtonMetroProveedor_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetroProveedor_ActionPerformed
        JFrameProveedor pro = new JFrameProveedor();
        pro.setVisible(true);
    }//GEN-LAST:event_rSButtonMetroProveedor_ActionPerformed

    private void rSButtonMetroCliente_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetroCliente_ActionPerformed
      JFrameClientes cli = new JFrameClientes();
        cli.setVisible(true);
    }//GEN-LAST:event_rSButtonMetroCliente_ActionPerformed

    private void rSButtonMSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMSalir1ActionPerformed
        JFrameLogin lol = new JFrameLogin();
        dispose();
        lol.setVisible(true);
    }//GEN-LAST:event_rSButtonMSalir1ActionPerformed

    void Panel(int x) {
        estado = x;
        switch (x) {
            case 1 -> {
                JPanelAdmin.setVisible(false);
                int pos = this.JPanelAdmin.getX();
//                if (pos < -1) {
////                    JpanelPrincipal.add(JPanelAdmin);
////                    Animacion.Animacion.mover_derecha(121, 0, 10, 2, JPanelAdmin);
//                }
            }
            case 2 -> {
                JPanelAuxiliar.setVisible(false);
//                int pos = this.JPanelAuxiliar.getX();
//                if (pos > -1) {
//                Animacion.Animacion.mover_derecha(0, -121, 10, 2, JPanelAuxiliar);

//                }
            }
        }
    }

    void estados() {

        switch (estado) {
            case 1 -> {
                if (val_admin == 0) {
                    JPanelAdmin.setVisible(true);
                    val_admin = 1;
                } else {
                    JPanelAdmin.setVisible(false);
                    val_admin = 0;
                }
            }

            case 2 -> {
                if (val_auxi == 0) {
                    JPanelAuxiliar.setVisible(true);
                    val_auxi = 1;
                } else {
                    JPanelAuxiliar.setVisible(false);
                    val_auxi = 0;
                }
            }
        }
    }

    void MostrarFechaYHora() {
        SimpleDateFormat formatoFechaHora = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Timer timer = new Timer(1000, (ActionEvent evt) -> {
            Date fechaHora = new Date();
            String fechaHoraStr = formatoFechaHora.format(fechaHora);
            jLFecha.setText(fechaHoraStr);
        });
        timer.start();
    }

    
    
    void mostrar(String pName, String sName, String pApellido, String sApellido, String tipo, int cc) {
       
         this.prueba.setText(""+cc);
         
        jLNombre.setText("");
        jLabelTipo.setText("");
        jLNombre.setText(pName+ " " + sName + " " + pApellido + " " + sApellido);
        jLabelTipo.setText(tipo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelAdmin;
    private javax.swing.JPanel JPanelAuxiliar;
    private javax.swing.JPanel JpanelPrincipal;
    private rsbuttom.RSButtonMetro RsBtInventario;
    private rsbuttom.RSButtonMetro RsBtInventario_;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel prueba;
    private rsbuttom.RSButtonMetro rSButtonMSalir;
    private rsbuttom.RSButtonMetro rSButtonMSalir1;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    private rsbuttom.RSButtonMetro rSButtonMetroCarteraC;
    private rsbuttom.RSButtonMetro rSButtonMetroCarteraP;
    private rsbuttom.RSButtonMetro rSButtonMetroCliente_;
    private rsbuttom.RSButtonMetro rSButtonMetroClientes;
    private rsbuttom.RSButtonMetro rSButtonMetroCompra;
    private rsbuttom.RSButtonMetro rSButtonMetroGasto;
    private rsbuttom.RSButtonMetro rSButtonMetroGasto_;
    private rsbuttom.RSButtonMetro rSButtonMetroProveedor;
    private rsbuttom.RSButtonMetro rSButtonMetroProveedor_;
    private rsbuttom.RSButtonMetro rSButtonMetroVenta;
    private rsbuttom.RSButtonMetro rSButtonMetroVenta_;
    private rsbuttom.RSButtonMetro rSButtonSeguridad;
    // End of variables declaration//GEN-END:variables
}
