/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import com.mysql.jdbc.PreparedStatement;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Sergio
 */
public class JFrameLogin extends javax.swing.JFrame {

    /**
     * Creates new form JFrameLogin
     */
    public int x = 0;
    public final int cont = 0;

    Conexion ConeBD = new Conexion();
    SoloMayusculas mayus = new SoloMayusculas();

    public JFrameLogin() {

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            this.setUndecorated(true);
            this.initComponents();
            this.setLocationRelativeTo(null);
            this.TxtUsuario.requestFocus();
            rsscalelabel.RSScaleLabel.setScaleLabel(jLabelLogo, "src/images/logo_220_2020.png");
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException err) {
        }
    }

    public void Validar() throws SQLException {
        String usuario = TxtUsuario.getText();
        String contrasena = sTxtPassUsuario.getText();
        try {

            String sql = "SELECT S.ESTADO_SEGURIDAD, S.ROLL_SEGURIDAD, E.CC_EMPLEADO, E.PNOM_EMPLEADO, E.SNOM_EMPLEADO, E.PAPE_EMPLEADO, E.SAPE_EMPLEADO "
                    + "FROM SEGURIDAD S "
                    + "JOIN CO_SEGURIDAD CS "
                    + "ON CS.SEGURIDAD_ID = S.ID_SEGURIDAD "
                    + "JOIN EMPLEADO E "
                    + "ON E.CC_EMPLEADO = S.CC_EMPLEADO_SEGURIDAD "
                    + "WHERE CS.USUARIO = ? AND CS.PASS = ?";
            try ( var preparedStatement = (PreparedStatement) ConeBD.BD.prepareStatement(sql)) {
                preparedStatement.setString(1, usuario);
                preparedStatement.setString(2, contrasena);

                try (ResultSet resultSet = preparedStatement.executeQuery()) {
                    if (resultSet.next()) {
                        int estadoSeguridad = resultSet.getInt("S.ESTADO_SEGURIDAD");
                        int rollSeguridad = resultSet.getInt("S.ROLL_SEGURIDAD");

                        if (estadoSeguridad == 1) {
                            String tipo = (rollSeguridad == 1) ? "ADMINISTRADOR" : "AUXILIAR";
                            x = (rollSeguridad == 1) ? 1 : 2;
                            String pName = resultSet.getString("E.PNOM_EMPLEADO");
                            String sName = resultSet.getString("E.SNOM_EMPLEADO");
                            String pApellido = resultSet.getString("E.PAPE_EMPLEADO");
                            String sApellido = resultSet.getString("E.SAPE_EMPLEADO");
                            int cc_empleado = resultSet.getInt("E.CC_EMPLEADO");
                            mostrarMenu(pName, sName, pApellido, sApellido, tipo, cc_empleado);

                        } else {
                            JOptionPane.showMessageDialog(null, "El usuario no está activo...");
                            limpiarCampos();
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Usuario o contraseña incorrectos");
                        limpiarCampos();
                    }
                }
            }
        } catch (HeadlessException | SQLException err) {
            err.printStackTrace();
        }
    }

    public void mostrarMenu(String pName, String sName, String pApellido, String sApellido, String tipo, int cedula) {
        JFrameMenu Pri = new JFrameMenu();
        Pri.mostrar(pName, sName, pApellido, sApellido, tipo, cedula);
        Pri.Panel(x);
        dispose();
        Pri.setVisible(true);
    }

    private void limpiarCampos() {
        TxtUsuario.setText("");
        sTxtPassUsuario.setText("");
        TxtUsuario.requestFocus();
    }

    public void camposValidar() throws SQLException {
        String usuario = TxtUsuario.getText();
        String contrasena = sTxtPassUsuario.getText();
        if (usuario.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe digitar un usuario y una contraseña");
            limpiarCampos();
        } else {

            Validar();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        TxtUsuario = new javax.swing.JTextField();
        sTxtPassUsuario = new javax.swing.JPasswordField();
        RsButtonIniciar = new rsbuttom.RSButtonMetro();
        RsButtonSalir = new rsbuttom.RSButtonMetro();
        jLabelLogo = new javax.swing.JLabel();
        JLabelConexion = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 3, 0, new java.awt.Color(206, 186, 36)));

        TxtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        TxtUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TxtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        TxtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)), "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });
        TxtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtUsuarioKeyTyped(evt);
            }
        });

        sTxtPassUsuario.setBackground(new java.awt.Color(255, 255, 255));
        sTxtPassUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sTxtPassUsuario.setForeground(new java.awt.Color(0, 0, 0));
        sTxtPassUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sTxtPassUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)), "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        sTxtPassUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        sTxtPassUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sTxtPassUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sTxtPassUsuarioKeyTyped(evt);
            }
        });

        RsButtonIniciar.setText("Entrar");
        RsButtonIniciar.setColorHover(new java.awt.Color(255, 51, 51));
        RsButtonIniciar.setColorNormal(new java.awt.Color(153, 0, 0));
        RsButtonIniciar.setColorPressed(new java.awt.Color(255, 204, 204));
        RsButtonIniciar.setColorTextPressed(new java.awt.Color(0, 0, 0));
        RsButtonIniciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RsButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RsButtonIniciarActionPerformed(evt);
            }
        });
        RsButtonIniciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RsButtonIniciarKeyPressed(evt);
            }
        });

        RsButtonSalir.setText("Salir");
        RsButtonSalir.setColorHover(new java.awt.Color(255, 51, 51));
        RsButtonSalir.setColorNormal(new java.awt.Color(153, 0, 0));
        RsButtonSalir.setColorPressed(new java.awt.Color(255, 204, 204));
        RsButtonSalir.setColorTextPressed(new java.awt.Color(0, 0, 0));
        RsButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RsButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RsButtonSalirActionPerformed(evt);
            }
        });

        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JLabelConexion.setBackground(new java.awt.Color(255, 255, 255));
        JLabelConexion.setForeground(new java.awt.Color(102, 255, 102));
        JLabelConexion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabelConexion.setText("Conexion ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(JLabelConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TxtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(sTxtPassUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(RsButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RsButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sTxtPassUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RsButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RsButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JLabelConexion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(109, 0, 25));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(109, 0, 25));
        jPanel5.setPreferredSize(new java.awt.Dimension(90, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Comercializadora de Carnes ");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Santos");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setPreferredSize(new java.awt.Dimension(318, 32));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RsButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RsButtonIniciarActionPerformed
        try {
            Validar();
        } catch (SQLException ex) {
            Logger.getLogger(JFrameLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_RsButtonIniciarActionPerformed

    private void RsButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RsButtonSalirActionPerformed
        System.exit(0);
        ConeBD.closeConexion_BD();
    }//GEN-LAST:event_RsButtonSalirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ConeBD.openConeccion_BD();
        JLabelConexion.setText(ConeBD.msgCone);
    }//GEN-LAST:event_formWindowOpened

    private void TxtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtUsuarioKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (!(TxtUsuario.getText().equals(""))) {
                sTxtPassUsuario.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Debe Ingresar un Usuario...");
                TxtUsuario.requestFocus();
            }
        }
    }//GEN-LAST:event_TxtUsuarioKeyPressed

    private void sTxtPassUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sTxtPassUsuarioKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (!(sTxtPassUsuario.getText().equals(""))) {
                RsButtonIniciar.requestFocus(true);
            } else {
                JOptionPane.showMessageDialog(null, "Debe Ingresar una contraseña...");
                sTxtPassUsuario.requestFocus();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_sTxtPassUsuarioKeyPressed

    private void TxtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtUsuarioKeyTyped
        char e = evt.getKeyChar();
        mayus.may(evt, e);
//        mayus.notNum(evt, e);
    }//GEN-LAST:event_TxtUsuarioKeyTyped

    private void sTxtPassUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sTxtPassUsuarioKeyTyped
        char e = evt.getKeyChar();
        mayus.num(evt, e);

    }//GEN-LAST:event_sTxtPassUsuarioKeyTyped

    private void RsButtonIniciarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RsButtonIniciarKeyPressed
        try {
            camposValidar();
        } catch (SQLException ex) {
            Logger.getLogger(JFrameLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RsButtonIniciarKeyPressed

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelConexion;
    private rsbuttom.RSButtonMetro RsButtonIniciar;
    private rsbuttom.RSButtonMetro RsButtonSalir;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField sTxtPassUsuario;
    // End of variables declaration//GEN-END:variables
}
