/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.awt.Font;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sergio
 */
public class JFrameCompras_proveedor extends javax.swing.JFrame {

    Conexion ConeBD = new Conexion();
    SoloMayusculas mayus = new SoloMayusculas();
    public int Ingreso = 0;
    public int id_gastos = 0;
    public int id_compra = 0;
    public int busqueda = 3;
    public String SqlMostrarT;
    DefaultTableModel DatosCliente;
    Object DatCliente[] = new Object[3];
    DefaultTableModel DatosCompras;
    Object DatCompra[] = new Object[5];
    int id_producto = 1;

    public JFrameCompras_proveedor() {

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            this.setUndecorated(true);
            initComponents();
            this.jlabelCc.setVisible(false);
            this.setExtendedState(MAXIMIZED_BOTH);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException err) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlabelCc = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldBcedula = new javax.swing.JTextField();
        jButtonBusqueda1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldBnombre = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldBapellido = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldIDcompra = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldnumeroFactura = new javax.swing.JTextField();
        jDateChooserfehca_registro = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jTextFieldValorkg = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldNombreP = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldCedulaP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxProducto = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        rSCrear = new rsbuttom.RSButtonMetro();
        rSCrear1 = new rsbuttom.RSButtonMetro();
        rSCrear3 = new rsbuttom.RSButtonMetro();
        rSCrear4 = new rsbuttom.RSButtonMetro();
        rSCrear5 = new rsbuttom.RSButtonMetro();
        rSCrear2 = new rsbuttom.RSButtonMetro();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaProveedor = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tablacompras = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(109, 0, 25));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("GESTIÓN DE COMPRAS - PROVEEDORES");
        jLabel12.setToolTipText("");

        jlabelCc.setBackground(new java.awt.Color(109, 0, 25));
        jlabelCc.setForeground(new java.awt.Color(109, 0, 25));
        jlabelCc.setEnabled(false);
        jlabelCc.setFocusable(false);

        jPanel4.setBackground(new java.awt.Color(109, 0, 25));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Lista de Provedores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("BUSCAR POR CÉDULA");

        jTextFieldBcedula.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldBcedula.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jTextFieldBcedula.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldBcedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBcedulaActionPerformed(evt);
            }
        });
        jTextFieldBcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBcedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBcedulaKeyTyped(evt);
            }
        });

        jButtonBusqueda1.setBackground(new java.awt.Color(109, 0, 25));
        jButtonBusqueda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons-search.png"))); // NOI18N
        jButtonBusqueda1.setToolTipText("");
        jButtonBusqueda1.setBorderPainted(false);
        jButtonBusqueda1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBusqueda1.setFocusPainted(false);
        jButtonBusqueda1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBusqueda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusqueda1ActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("BUSCAR POR NOMBRE");

        jTextFieldBnombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldBnombre.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jTextFieldBnombre.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldBnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBnombreActionPerformed(evt);
            }
        });
        jTextFieldBnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBnombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBnombreKeyTyped(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("BUSCAR POR APELLIDO");

        jTextFieldBapellido.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldBapellido.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jTextFieldBapellido.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldBapellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBapellidoActionPerformed(evt);
            }
        });
        jTextFieldBapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBapellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBapellidoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldBapellido)
                    .addComponent(jTextFieldBnombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBcedula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBusqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBusqueda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41))
        );

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(255, 255, 255)));

        jPanel5.setBackground(new java.awt.Color(109, 0, 25));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Registro de compra", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ID");

        jTextFieldIDcompra.setEditable(false);
        jTextFieldIDcompra.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIDcompra.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jTextFieldIDcompra.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldIDcompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIDcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDcompraActionPerformed(evt);
            }
        });
        jTextFieldIDcompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldIDcompraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDcompraKeyTyped(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("FECHA");

        jTextFieldnumeroFactura.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldnumeroFactura.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jTextFieldnumeroFactura.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldnumeroFactura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldnumeroFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnumeroFacturaActionPerformed(evt);
            }
        });
        jTextFieldnumeroFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldnumeroFacturaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldnumeroFacturaKeyTyped(evt);
            }
        });

        jDateChooserfehca_registro.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooserfehca_registro.setForeground(new java.awt.Color(0, 0, 0));
        jDateChooserfehca_registro.setDateFormatString("y/MM/d");
        jDateChooserfehca_registro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jDateChooserfehca_registro.setOpaque(false);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("N° Factura");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("PESO KL");

        jTextFieldPeso.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPeso.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jTextFieldPeso.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesoActionPerformed(evt);
            }
        });
        jTextFieldPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPesoKeyTyped(evt);
            }
        });

        jTextFieldValorkg.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValorkg.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jTextFieldValorkg.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldValorkg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldValorkg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorkgActionPerformed(evt);
            }
        });
        jTextFieldValorkg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldValorkgKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldValorkgKeyTyped(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("VALOR  KL");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ESTADO");

        jComboBoxEstado.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxEstado.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jComboBoxEstado.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "PENDIENTE", "PAGADO" }));
        jComboBoxEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });
        jComboBoxEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxEstadoKeyPressed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("PROVEEDOR");

        jTextFieldNombreP.setEditable(false);
        jTextFieldNombreP.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNombreP.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jTextFieldNombreP.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNombreP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombrePActionPerformed(evt);
            }
        });
        jTextFieldNombreP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombrePKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombrePKeyTyped(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("CÉDULA");

        jTextFieldCedulaP.setEditable(false);
        jTextFieldCedulaP.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCedulaP.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jTextFieldCedulaP.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCedulaP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCedulaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedulaPActionPerformed(evt);
            }
        });
        jTextFieldCedulaP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCedulaPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCedulaPKeyTyped(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PRODUCTO");

        jComboBoxProducto.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxProducto.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jComboBoxProducto.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "PENDIENTE", "PAGADO" }));
        jComboBoxProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductoActionPerformed(evt);
            }
        });
        jComboBoxProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxProductoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIDcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldnumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserfehca_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorkg, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCedulaP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldIDcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldnumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooserfehca_registro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCedulaP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldValorkg, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jlabelCc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1312, 1312, 1312)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 1404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelCc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(109, 0, 25));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(255, 255, 255)));

        rSCrear.setText("EDITAR");
        rSCrear.setColorHover(new java.awt.Color(204, 0, 0));
        rSCrear.setColorNormal(new java.awt.Color(255, 204, 204));
        rSCrear.setColorPressed(new java.awt.Color(51, 0, 0));
        rSCrear.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSCrearActionPerformed(evt);
            }
        });

        rSCrear1.setText("NUEVO");
        rSCrear1.setColorHover(new java.awt.Color(204, 0, 0));
        rSCrear1.setColorNormal(new java.awt.Color(255, 204, 204));
        rSCrear1.setColorPressed(new java.awt.Color(51, 0, 0));
        rSCrear1.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSCrear1ActionPerformed(evt);
            }
        });

        rSCrear3.setText("Cerrar");
        rSCrear3.setColorHover(new java.awt.Color(204, 0, 0));
        rSCrear3.setColorNormal(new java.awt.Color(255, 204, 204));
        rSCrear3.setColorPressed(new java.awt.Color(51, 0, 0));
        rSCrear3.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSCrear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSCrear3ActionPerformed(evt);
            }
        });

        rSCrear4.setText("AGREGAR");
        rSCrear4.setColorHover(new java.awt.Color(204, 0, 0));
        rSCrear4.setColorNormal(new java.awt.Color(255, 204, 204));
        rSCrear4.setColorPressed(new java.awt.Color(51, 0, 0));
        rSCrear4.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSCrear4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSCrear4ActionPerformed(evt);
            }
        });

        rSCrear5.setText("COMPRAR\tPRODUCTOS");
        rSCrear5.setToolTipText("");
        rSCrear5.setColorHover(new java.awt.Color(204, 0, 0));
        rSCrear5.setColorNormal(new java.awt.Color(255, 204, 204));
        rSCrear5.setColorPressed(new java.awt.Color(51, 0, 0));
        rSCrear5.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSCrear5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSCrear5ActionPerformed(evt);
            }
        });

        rSCrear2.setText("ELIMINAR");
        rSCrear2.setColorHover(new java.awt.Color(204, 0, 0));
        rSCrear2.setColorNormal(new java.awt.Color(255, 204, 204));
        rSCrear2.setColorPressed(new java.awt.Color(51, 0, 0));
        rSCrear2.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSCrear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSCrear2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSCrear3, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(rSCrear5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSCrear4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSCrear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSCrear1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSCrear2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(rSCrear1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCrear4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCrear2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSCrear5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSCrear3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaProveedor.setOpaque(false);
        TablaProveedor.setSelectionBackground(new java.awt.Color(255, 204, 204));
        TablaProveedor.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TablaProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProveedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaProveedor);

        Tablacompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tablacompras.setOpaque(false);
        Tablacompras.setSelectionBackground(new java.awt.Color(255, 204, 204));
        Tablacompras.setSelectionForeground(new java.awt.Color(0, 0, 0));
        Tablacompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablacomprasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Tablacompras);

        jPanel6.setBackground(new java.awt.Color(109, 0, 25));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1402, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void mostrarDatosTabla() {
        TablaProveedor.clearSelection();
        DatosCliente = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        TablaProveedor.setModel(DatosCliente);
        DatosCliente.addColumn("Cédula");
        DatosCliente.addColumn("Primer nombre");
        DatosCliente.addColumn("Primer apellido");
        DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) TablaProveedor.getTableHeader().getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);
        TablaProveedor.setRowHeight(30);
        Font headerFont = headerRenderer.getFont();
        Font newHeaderFont = new Font(headerFont.getName(), Font.BOLD, 14);
        TablaProveedor.getTableHeader().setFont(newHeaderFont);
        TablaProveedor.getTableHeader().setReorderingAllowed(false);
        TablaProveedor.getTableHeader().setResizingAllowed(false);

        switch (busqueda) {
            case 0 -> {
                if (jTextFieldBcedula.getText().length() >= 8) {
                    SqlMostrarT = "SELECT CC_PROVEEDOR, PNOM_PROVEEDOR, PAPE_PROVEEDOR FROM PROVEEDOR WHERE CC_PROVEEDOR= " + jTextFieldBcedula.getText() + " ORDER BY PNOM_PROVEEDOR";
                } else {
//                    borraCamposr();
                    jTextFieldBcedula.requestFocus();
                    busqueda = 3;
                    mostrarDatosTabla();
                }
            }
            case 1 -> {
                SqlMostrarT = "SELECT CC_PROVEEDOR, PNOM_PROVEEDOR, PAPE_PROVEEDOR FROM PROVEEDOR WHERE  PNOM_PROVEEDOR  LIKE '%" + jTextFieldBnombre.getText() + "%' ORDER BY PNOM_PROVEEDOR";
            }

            case 2 -> {

                SqlMostrarT = "SELECT CC_PROVEEDOR, PNOM_PROVEEDOR, PAPE_PROVEEDOR FROM PROVEEDOR WHERE  PAPE_PROVEEDOR  LIKE '%" + jTextFieldBapellido.getText() + "%' ORDER BY PNOM_PROVEEDOR";

            }
            case 3 -> {
                SqlMostrarT = "SELECT CC_PROVEEDOR, PNOM_PROVEEDOR, PAPE_PROVEEDOR FROM PROVEEDOR ORDER BY PNOM_PROVEEDOR";
            }

        }

        try {
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlMostrarT);

            if (ConeBD.RstBD != null && ConeBD.RstBD.next()) {
                do {
                    DatCliente[0] = ConeBD.RstBD.getString("CC_PROVEEDOR");
                    DatCliente[1] = ConeBD.RstBD.getString("PNOM_PROVEEDOR");
                    DatCliente[2] = ConeBD.RstBD.getString("PAPE_PROVEEDOR");
                    DatosCliente.addRow(DatCliente);
                } while (ConeBD.RstBD.next());
            } else {
                if (busqueda == 0) {
                    busqueda = 3;
                    JOptionPane.showMessageDialog(rootPane, "No se encontró algún proveedor con  cédula, " + jTextFieldBcedula.getText());
//                    borraCamposr();
                    mostrarDatosTabla();
                }
                if (busqueda == 1) {
                    busqueda = 3;
                    JOptionPane.showMessageDialog(rootPane, "No se encontró algún proveedor con el nombre, " + jTextFieldBnombre.getText());
//                    borraCamposr();
                    mostrarDatosTabla();

                }
                if (busqueda == 2) {
                    busqueda = 3;
                    JOptionPane.showMessageDialog(rootPane, "No se encontró algún proveedor con el apellido, " + jTextFieldBapellido.getText());
//                    borraCamposr();
                    mostrarDatosTabla();

                }

            }

        } catch (SQLException err) {
            err.printStackTrace();
        } finally {

        }
    }

    void mostrarDatosTablaCompra() {
        Tablacompras.clearSelection();
        DatosCompras = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        Tablacompras.setModel(DatosCompras);
        DatosCompras.addColumn("Producto");
        DatosCompras.addColumn("Peso kg");
        DatosCompras.addColumn("Valor kg");
        DatosCompras.addColumn("Valor total");
        DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) Tablacompras.getTableHeader().getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);
        Tablacompras.setRowHeight(30);
        Font headerFont = headerRenderer.getFont();
        Font newHeaderFont = new Font(headerFont.getName(), Font.BOLD, 14);
        Tablacompras.getTableHeader().setFont(newHeaderFont);
        Tablacompras.getTableHeader().setReorderingAllowed(false);
        Tablacompras.getTableHeader().setResizingAllowed(false);

        String sqlProductos = "SELECT P.NOMBRE_PRODUCTO, P.PESO_PRODUCTO_KL, P.VALOR_KG, P.VALOR_COMPRA "
                + "FROM DESC_PRODUCTOS P JOIN COMPRA_PRODUCTOS CP "
                + "ON P.ID_PRODUCTO = CP.ID_PROD_FK "
                + "WHERE CP.ID_COMPRA_FK = " + id_compra + " GROUP BY P.ID_PRODUCTO ORDER BY P.NOMBRE_PRODUCTO ";
        try {
            System.out.println(sqlProductos);
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(sqlProductos);
            if (ConeBD.RstBD != null && ConeBD.RstBD.next()) {
                do {
                    DatCompra[0] = ConeBD.RstBD.getString("P.NOMBRE_PRODUCTO");
                    DatCompra[1] = ConeBD.RstBD.getString("P.PESO_PRODUCTO_KL");
                    DatCompra[2] = ConeBD.RstBD.getString("P.VALOR_KG");
                    DatCompra[3] = ConeBD.RstBD.getString("P.VALOR_COMPRA");
                    DatosCompras.addRow(DatCompra);
                } while (ConeBD.RstBD.next());
                 TablaProveedor.clearSelection();
            }
        } catch (SQLException e) {
        }
        
    }

    public void agregarProducto() {

        switch (Ingreso) {
            case 1 -> {

                if (jComboBoxProducto.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(null, "Debe seleccionar un producto...");
                    break;
                }
                if (jTextFieldPeso.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Debe ingresar el peso del producto");
                    break;
                }
                if (jTextFieldValorkg.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Debe Ingresar el precio del kg");
                    break;
                }
                agregaProducto();
            }

            case 2 -> {
                editarProducto();
            }

            default -> {
            }

        }
    }

    public void agregaProducto() {

        String id_prod = "SELECT MAX(id_producto)+1 'MAXIMO' FROM DESC_PRODUCTOS";
        try {
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(id_prod);
            if (ConeBD.RstBD.next()) {
                id_producto = Integer.parseInt(ConeBD.RstBD.getString("MAXIMO"));
            }
        } catch (Exception e) {
        }

        String sqlGuardarProducto = "INSERT INTO DESC_PRODUCTOS VALUES (" + id_producto + ",'" + jComboBoxProducto.getSelectedItem() + "'," + jTextFieldPeso.getText() + ",'" + jTextFieldValorkg.getText() + "','" + Double.parseDouble(jTextFieldPeso.getText()) * Double.parseDouble(jTextFieldValorkg.getText()) + "')";
        System.out.println(sqlGuardarProducto);
        try {
            ConeBD.StmBD.executeUpdate(sqlGuardarProducto);

        } catch (Exception e) {
            e.printStackTrace();

        }

        String compra_prod = "INSERT INTO COMPRA_PRODUCTOS VALUES (" + id_compra + "," + id_producto + ")";
        System.out.println(compra_prod);
        try {
            ConeBD.StmBD.executeUpdate(compra_prod);

        } catch (Exception e) {
            e.printStackTrace();

        }

        mostrarDatosTablaCompra();

    }

    public void editarProducto() {

    }

    public void eliminarProducto() {

    }

    public void guardarFacturaCompra() {
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        String fechaFormateada = formatoFecha.format(jDateChooserfehca_registro.getDate());
        String sqlGuardarCompra = "INSERT INTO COMPRAS VALUES (" + id_compra + ",'" + fechaFormateada + "','" + jTextFieldnumeroFactura.getText() + "','" + jComboBoxEstado.getSelectedItem() + "'," + jTextFieldCedulaP.getText() + ")";
        System.out.println(sqlGuardarCompra);
        try {
            ConeBD.StmBD.executeUpdate(sqlGuardarCompra);
            id_compra = 0;

        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    public void compraID() {
        String id_comp;
        try {
            id_comp = "SELECT MAX(id_compra)+1 'MAXIMO' FROM COMPRAS";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(id_comp);
            if (ConeBD.RstBD.next()) {
                System.out.println(id_comp);
                id_compra = Integer.parseInt(ConeBD.RstBD.getString("MAXIMO"));
            }

        } catch (NumberFormatException | SQLException e) {
        }
        jTextFieldIDcompra.setText("" + id_compra);
    }

    public void prender() {
        jTextFieldnumeroFactura.setEnabled(true);
        jTextFieldPeso.setEnabled(true);
        jTextFieldValorkg.setEnabled(true);
        jComboBoxEstado.setEnabled(true);
        jComboBoxProducto.setEnabled(true);
    }

    public void apagar() {
        jTextFieldnumeroFactura.setEnabled(false);
        jTextFieldPeso.setEnabled(false);
        jTextFieldValorkg.setEnabled(false);
        jComboBoxEstado.setEnabled(false);
        jComboBoxProducto.setEnabled(false);
    }

    public void limpiar() {
        jTextFieldnumeroFactura.setText("");
        jTextFieldPeso.setText("");
        jTextFieldValorkg.setText("");
        jComboBoxEstado.setSelectedIndex(0);
        jComboBoxProducto.setSelectedIndex(0);
    }


    private void rSCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSCrearActionPerformed
        Ingreso = 2;
        prender();

    }//GEN-LAST:event_rSCrearActionPerformed

    private void rSCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSCrear1ActionPerformed
        Ingreso = 1;
        prender();


    }//GEN-LAST:event_rSCrear1ActionPerformed

    private void rSCrear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSCrear3ActionPerformed
        ConeBD.closeConexion_BD();
        dispose();
    }//GEN-LAST:event_rSCrear3ActionPerformed

    private void rSCrear4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSCrear4ActionPerformed
        agregarProducto();
    }//GEN-LAST:event_rSCrear4ActionPerformed

    private void rSCrear5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSCrear5ActionPerformed
        guardarFacturaCompra();
        limpiar();
       mostrarDatosTablaCompra();



    }//GEN-LAST:event_rSCrear5ActionPerformed

    private void TablaProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProveedorMouseClicked
        int fila = TablaProveedor.getSelectedRow();
        int Columna0 = 0, Columna1 = 1;
        jTextFieldCedulaP.setText(String.valueOf(this.TablaProveedor.getValueAt(fila, Columna0)));
        jTextFieldNombreP.setText(String.valueOf(this.TablaProveedor.getValueAt(fila, Columna1)));
    }//GEN-LAST:event_TablaProveedorMouseClicked

    private void TablacomprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablacomprasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablacomprasMouseClicked

    private void jButtonBusqueda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusqueda1ActionPerformed
        if (!jTextFieldBcedula.getText().isEmpty()) {
            busqueda = 0;
            mostrarDatosTabla();
        }

        if (!jTextFieldBnombre.getText().isEmpty()) {
            busqueda = 1;
            mostrarDatosTabla();
        }
        if (!jTextFieldBapellido.getText().isEmpty()) {
            busqueda = 2;
            mostrarDatosTabla();
        }

        if (jTextFieldBcedula.getText().isEmpty() && jTextFieldBnombre.getText().isEmpty() && jTextFieldBapellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Digite almenos un parametro de busqueda...");
            busqueda = 3;
            mostrarDatosTabla();
        }
    }//GEN-LAST:event_jButtonBusqueda1ActionPerformed

    public void fechaMostrar() {
        this.jDateChooserfehca_registro.setEnabled(false);
        Date fecha = new Date();
        jDateChooserfehca_registro.setDateFormatString("yyyy-MM-dd");
        jDateChooserfehca_registro.setDate(fecha);
    }


    private void jTextFieldBcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBcedulaKeyTyped
        char e = evt.getKeyChar();
        mayus.num(evt, e);
    }//GEN-LAST:event_jTextFieldBcedulaKeyTyped

    private void jTextFieldBcedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBcedulaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBcedulaKeyPressed

    private void jTextFieldBcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBcedulaActionPerformed

    private void jTextFieldBnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBnombreActionPerformed

    private void jTextFieldBnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBnombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBnombreKeyPressed

    private void jTextFieldBnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBnombreKeyTyped
        char e = evt.getKeyChar();
        mayus.may(evt, e);
        mayus.notNum(evt, e);
    }//GEN-LAST:event_jTextFieldBnombreKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ConeBD.openConeccion_BD();
        mostrarDatosTabla();
        mostrarDatosTablaCompra();
        fechaMostrar();
        compraID();
        apagar();

    }//GEN-LAST:event_formWindowOpened

    private void jTextFieldIDcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDcompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDcompraActionPerformed

    private void jTextFieldIDcompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDcompraKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDcompraKeyPressed

    private void jTextFieldIDcompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDcompraKeyTyped
        char e = evt.getKeyChar();
        mayus.num(evt, e);
    }//GEN-LAST:event_jTextFieldIDcompraKeyTyped

    private void jTextFieldnumeroFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnumeroFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnumeroFacturaActionPerformed

    private void jTextFieldnumeroFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnumeroFacturaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnumeroFacturaKeyPressed

    private void jTextFieldnumeroFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnumeroFacturaKeyTyped
        char e = evt.getKeyChar();
        mayus.may(evt, e);
    }//GEN-LAST:event_jTextFieldnumeroFacturaKeyTyped

    private void jTextFieldPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesoActionPerformed

    private void jTextFieldPesoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesoKeyPressed

    private void jTextFieldPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesoKeyTyped

    private void jTextFieldValorkgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorkgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorkgActionPerformed

    private void jTextFieldValorkgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorkgKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorkgKeyPressed

    private void jTextFieldValorkgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorkgKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorkgKeyTyped

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void jComboBoxEstadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxEstadoKeyPressed
//        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
//            if (!(jComboBoxEstado.getSelectedItem().equals("SELECCIONAR"))) {
//                jComboBoxTipo.requestFocus();
//            } else {
//                JOptionPane.showMessageDialog(null, "Debe seleccionar un estado");
//                jComboBoxEstado.requestFocus();
//            }
//        }
    }//GEN-LAST:event_jComboBoxEstadoKeyPressed

    private void jTextFieldCedulaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaPActionPerformed

    private void jTextFieldCedulaPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCedulaPKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaPKeyPressed

    private void jTextFieldCedulaPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCedulaPKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaPKeyTyped

    private void jTextFieldBapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBapellidoActionPerformed

    private void jTextFieldBapellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBapellidoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBapellidoKeyPressed

    private void jTextFieldBapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBapellidoKeyTyped
        char e = evt.getKeyChar();
        mayus.may(evt, e);
        mayus.notNum(evt, e);
    }//GEN-LAST:event_jTextFieldBapellidoKeyTyped

    private void jComboBoxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProductoActionPerformed

    private void jComboBoxProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxProductoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProductoKeyPressed

    private void jTextFieldNombrePKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombrePKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombrePKeyTyped

    private void jTextFieldNombrePKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombrePKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombrePKeyPressed

    private void jTextFieldNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombrePActionPerformed

    private void rSCrear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSCrear2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSCrear2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCompras_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCompras_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCompras_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCompras_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCompras_proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProveedor;
    private javax.swing.JTable Tablacompras;
    private javax.swing.JButton jButtonBusqueda1;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxProducto;
    private com.toedter.calendar.JDateChooser jDateChooserfehca_registro;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldBapellido;
    private javax.swing.JTextField jTextFieldBcedula;
    private javax.swing.JTextField jTextFieldBnombre;
    private javax.swing.JTextField jTextFieldCedulaP;
    private javax.swing.JTextField jTextFieldIDcompra;
    private javax.swing.JTextField jTextFieldNombreP;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JTextField jTextFieldValorkg;
    private javax.swing.JTextField jTextFieldnumeroFactura;
    private javax.swing.JLabel jlabelCc;
    private rsbuttom.RSButtonMetro rSCrear;
    private rsbuttom.RSButtonMetro rSCrear1;
    private rsbuttom.RSButtonMetro rSCrear2;
    private rsbuttom.RSButtonMetro rSCrear3;
    private rsbuttom.RSButtonMetro rSCrear4;
    private rsbuttom.RSButtonMetro rSCrear5;
    // End of variables declaration//GEN-END:variables
}
